### ISSUE TITLE
Stream name in home-assistant UI

### ISSUE THREAD

**Issue by pbros** [happyleavesaoc/python-snapcast#1]
Hello,

When selecting which stream is used for each snapclient, would it be possible to see the name of the stream instead of the path if it is specified in the snapserver configuration? It would make it cleaner and increase the WAF.

For example, if I have configured my snapserver with

-s pipe:///tmp/snapfifo?name=Radio
-s pipe:///tmp/snapfifompd?name=Mpd

I would like to see "Radio" and "Mpd" in the UI instead of "pipe:///tmp/snapfifo" and "pipe:///tmp/snapfifompd"

This is currently how the snapcast android app behaves.

Thank you!

**Comment by happyleavesaoc** [comment]
It is possible, just some extra mapping logic between stream url and name has to be added. This is on my TODO list, but not a high priority. It will require at minimum a change to the Home Assistant component, and possibly a change to this repository to make the interface cleaner.
