### ISSUE TITLE
Updating python-snapcast to 2.0.7

### ISSUE THREAD

**Issue by fallenicarus** [happyleavesaoc/python-snapcast#14]
I am running the latest HA version but I see the asyncio error - on the HA forum and here it seems upgrading to 2.0.7 should solve the issue I see. I have a HA setup running in a python virtualenv.

I have tried running "python3 -m pip uninstall snapcast" and then doing "pip install -I  snapcast==2.0.7" (I have also tried "pip install --upgrade snapcast"). After doing both things, I see the site-packages folder showing me snapcast 2.0.7 as a folder and I see messages along the lines of snapcast version 2.0.7 installed. 

When i run HA, I still see the asyncio message and now when i check the site-packages folder, I see 2.0.6 - somehow the newer version of python-snapcast seems to be replaced by the older version. 

Any ideas/help in this problem would be great!

**Comment by happyleavesaoc** [comment]
This is a Home Assistant problem, not a `python-snapcast` problem. Home Assistant needs to set version `2.0.7` in the requirements.

**Comment by happyleavesaoc** [comment]
Home Assistant now uses `1.0.7`: https://github.com/home-assistant/home-assistant/pull/9100

It's available now if you use the `dev` branch, otherwise wait for the next numbered release.
