### ISSUE TITLE
Best way to get server update in realtime

### ISSUE THREAD

**Issue by de666** [happyleavesaoc/python-snapcast#24]
How to get realtime server updates?
There are only callbacks for connection, disconnection and new_client_update.
If I want to handle all the server updates (for example stream status update), which is the best way to do it?

**Comment by m-zander** [comment]
Would need to add support for more callbacks. Should be able to implement them in the same manner as existing callbacks.

**Comment by happyleavesaoc** [comment]
Add callbacks that correspond to each of the various updates. Probably could use a refactor of the callback setting at that point, maybe a signature like `set_callback(self, event, func)` PR welcome!
