### ISSUE TITLE
Snapcast 0.16.x features

### ISSUE THREAD

**Issue by uSpike** [happyleavesaoc/python-snapcast#31]
Hi, I just wanted to document that there's some new features in snapcast 0.16.0 that would be great to integrate into this project.  See https://github.com/badaix/snapcast/blob/master/changelog.md#version-0160

Notable changes:
* Streams can be added and removed
* Group names can be changed

Maybe the control interface could expose additional functionality if the sever version is higher than 0.16.0?  I may be able to write up a PR in the next few days.

**Comment by happyleavesaoc** [comment]
Ability to change group names is a big one, nice.

It's probably sufficient to raise an exception if the server version is not `>= 0.16.0`.

I welcome a PR. Unfortunately I don't have time in the near future to add support myself.

**Comment by markferry** [comment]
I started working on this: [group-set-name](/markferry/python-snapcast/tree/group-set-name).

**Comment by markferry** [comment]
#40

**Comment by SantiagoSotoC** [comment]
I add support for add and remove streams
#57
