### ISSUE TITLE
Server updates troubles

### ISSUE THREAD

**Issue by StalkerSVR** [happyleavesaoc/python-snapcast#32]
Is there an example of how to use callbacks? I want to write a little script that does some things when the state of a thread changes. Everything is installed on Orange Pi (Armbian).
I thought that the internal variables of the server object are changing in the background, then something was happening on the snapcast server. But when I stop one of the streams, the state of the stream in the server object does not change :( I have to close my script and restart it again to get the new status of the stream from the server, but I think this is only because of my misunderstanding of the logic of the script

**Comment by dmckminard** [comment]
Have you a found a solution for your issue ? :/

**Comment by happyleavesaoc** [comment]
There's an example in the Home Assistant component (which uses this module): https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/snapcast/media_player.py#L205

**Comment by TheIdenty** [comment]
@happyleavesaoc  Could you explain me a bit closer on how to use the callbacks? I want the attributes of Server,Client and Groups to be up-to-date whenever I access them. As far as I understood thats what the callbacks are there for. 
Searching the code didn't bring me any further nor did the link you posted above.
Could you just add a code snippet to explain this? Would be awesome :D
