### ISSUE TITLE
Mimic Snapweb Group Volume Control

### ISSUE THREAD

**Issue by D3v01dZA** [happyleavesaoc/python-snapcast#36]
When changing a groups volume, all speakers in the group are changed to the same volume. The usefulness of this seems dubious and I'd prefer that it changes the clients in the group's volumes relative to what they were before changing since this normalizes the volume in the group - Snapweb does this.

I'm happy to make a PR but I wasn't sure if this was something that the project would want, the relevant code is [Python-Snapcast](https://github.com/happyleavesaoc/python-snapcast/blob/master/snapcast/control/group.py#L72) and [Snapcast](https://github.com/badaix/snapcast/blob/master/server/etc/snapweb/snapcontrol.js#L483).

**Comment by happyleavesaoc** [comment]
Makes sense. PR would be merged if you submitted.

**Comment by happyleavesaoc** [comment]
Published `2.1.2` to pypi.
