### ISSUE TITLE
[discussion] Group friendly name

### ISSUE THREAD

**Issue by luar123** [happyleavesaoc/python-snapcast#54]
At the moment the friendly name of a group is either the name (if manually set) or the stream name: `return self.name if self.name != '' else self.stream`
By default there are no names set and multiple groups could have the same stream, thus showing the same friendly name. In my opinion this makes sense only if someone is using exactly one group per stream and in that case one could set the group name manually.
So I would propose to change the fall-back to either the group id or a combination of client names.

**Comment by happyleavesaoc** [comment]
Yes
