### ISSUE TITLE
Notification for server disconnection

### ISSUE THREAD

**Issue by airdrummingfool** [happyleavesaoc/python-snapcast#7]
Hello,
It would be nice to have some kind of notification if the snapserver disconnects. For example, the source process my snapserver reads from is flaky and tends to crash, breaking the pipe and bringing snapserver down with it. Since I'm running snapserver as a service, it recovers almost instantly, but my `python-snapcast`-based project silently loses its connection and then hangs the next time I use `run_until_complete` to run a snapclient command.

If you agree, I'm happy to work up a PR, however I'd like some guidance as Python isn't really my specialty. Here are a couple potential implementations (neither of which are perfect):

Since `SnapcastProtocol` is a subclass of `asyncio.Protocol`, we can implement `connection_lost`, which will alert the `SnapcastProtocol` class, however I'm not sure how best to bubble that up to the `Snapserver` class for dissemination. Perhaps a callback in the `_callbacks` map that maps `SERVER_ONDISCONNECT` to a disconnect function in the Server class? That seems a tiny bit hackish since `OnDisconnect` isn't a real snapcast notification, but it's useful to have the callbacks all together (plus it's doubtful there'd ever be a real snapserver notification called `OnDisconnect`). Extending that there could also be a matching `SERVER_ONCONNECT` callback as well.

Alternatively, a simple boolean `connected` property could be added to the `SnapcastProtocol` class and made available through a getter on the `Snapserver` class. This would be much easier to implement, but the disadvantage is that it would need to be polled.

Thanks!

**Comment by happyleavesaoc** [comment]
Hi, I like the artificial `SERVER_ON[DISCONNECT/CONNECT]` notifications via callback. I think your implementation idea sounds good.

**Comment by airdrummingfool** [comment]
Fixed in #8!
